#!/usr/bin/bash

cd "$(dirname "$0")"

[ -d "../build" ] && rm -r ../build
mkdir ../build

for dir in $(ls -d ../G*); 
do
 	cp $dir/* .;
done;

for file in $(ls -d *.js);
do
	echo $file >> jsInput.txt;
done;

./builder.sh -c jsInput.txt ../build/libs.min.js

for file in $(ls -d *.css);
do
	cat $file >> ../build/libs.css;
done;

cp *.html ../build/

wget ftp://176.102.64.23/public/libs/libsInfo.json 

awk -F'["]' -v OFS='"'  '/"version":/{
    split($4,a,".");
    $4=a[1]"."a[2]"."a[3]+1
    }
;1' libsInfo.json > ../build/libsInfo.json

./clear
